# Introduction to NumPy

### What is NumPy?

- **NumPy (Numerical Python)** is a Python library for fast numerical computing.
- It provides a powerful data structure called **ndarray (N-dimensional Array)**.
- NumPy is faster and more memory-efficient than Python lists for numerical data.
- It is the foundation of libraries like **Pandas, Matplotlib, Scikit-learn, TensorFlow, and PyTorch**.

### Importing NumPy

```python
import numpy as np
```

- `np` is the standard alias used by the Python community.
- It makes the code shorter and easier to read.

In [1]:
import numpy as np
print(np.__version__)

2.3.5


## Why NumPy?

Python lists are flexible but slower for numerical computations.

**Python List**
- Can store multiple data types
- Slower
- More memory

**NumPy Array**
- Stores one data type
- Faster
- Memory efficient

In [2]:
numbers = [10,"Hello",3.14,True]
print(numbers)

[10, 'Hello', 3.14, True]


In [3]:
print(type(numbers))

<class 'list'>


In [4]:
arr = np.array([10,20,30,])
print(arr)
print(type(arr))

[10 20 30]
<class 'numpy.ndarray'>


ndarray = N-dimensional Array

In [5]:
A = np.array([1,2,3])
B = np.array([[1,2,3]])

print(A.ndim)
print(B.ndim)

1
2


In [6]:
A = np.array(10)
print(A)
print(A.ndim)

10
0


## Array Dimensions

- 0D → Single value
- 1D → One-dimensional array (vector)
- 2D → Two-dimensional array (rows and columns)
- 3D → Collection of 2D arrays
- `ndim` returns the number of dimensions of an array.

In [7]:
A = np.array([
    [10,20,30],
    [40,50,60]
])
print(A.shape)

(2, 3)


In [8]:
print(type(A.shape))

<class 'tuple'>


In [9]:
A = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(A.ndim)
print(A.shape)

3
(2, 2, 2)


In [10]:
A = np.array([
    [
        [1, 2, 3, 4]
    ],
    [
        [5, 6, 7, 8]
    ]
])
print(A.ndim)
print(A.shape)

3
(2, 1, 4)


## NumPy Array Attributes

### `ndim`
- Returns the **number of dimensions** of an array.
- 1D → `(elements,)`
- 2D → `(rows, columns)`
- 3D → `(tables, rows, columns)`

### `shape`
- Returns the **size of each dimension** as a tuple.
- Count from the **outermost brackets inward**.

### `size`
- Returns the **total number of elements** in the array.

### `itemsize`
- Returns the **memory (in bytes)** occupied by **one element**.

### `nbytes`
- Returns the **total memory (in bytes)** occupied by the entire array.

> Formula:
>
> `nbytes = size × itemsize`

In [11]:
A = np.array([10, 20, 30])

print(A.dtype)

int64


In [12]:
A = np.array([10, 20, 30])
print(A.dtype)
B = np.array([10.5, 20.8, 30.2])
print(B.dtype)

int64
float64


In [16]:
A = np.array([10, 20, 30])

print("Array:", A)
print("ndim:", A.ndim)
print("shape:", A.shape)
print("size:", A.size)
print("itemsize:", A.itemsize)
print("nbytes:", A.nbytes)
print("dtype:", A.dtype)

Array: [10 20 30]
ndim: 1
shape: (3,)
size: 3
itemsize: 8
nbytes: 24
dtype: int64


In [14]:
A = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Array:\n", A)
print("ndim:", A.ndim)
print("shape:", A.shape)
print("size:", A.size)
print("itemsize:", A.itemsize)
print("nbytes:", A.nbytes)
print("dtype:", A.dtype)

Array:
 [[10 20 30]
 [40 50 60]]
ndim: 2
shape: (2, 3)
size: 6
itemsize: 8
nbytes: 48
dtype: int64


In [15]:
A = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print("Array:\n", A)
print("ndim:", A.ndim)
print("shape:", A.shape)
print("size:", A.size)
print("itemsize:", A.itemsize)
print("nbytes:", A.nbytes)
print("dtype:", A.dtype)

Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
ndim: 3
shape: (2, 2, 2)
size: 8
itemsize: 8
nbytes: 64
dtype: int64



### Memory Formula

```
nbytes = size × itemsize
```

In [17]:
A = np.array([10, 20, 30])
print(len(A))

3


## `len()` Function

- Returns the **size of the first (outermost) dimension** of a NumPy array.
- It is **not** the total number of elements.
- Equivalent to:

```python
len(A) == A.shape[0]
```

In [18]:
import numpy as np

A = np.array([10, 20, 30])

print("Array:", A)
print("len(A):", len(A))
print("shape:", A.shape)
print("size:", A.size)

Array: [10 20 30]
len(A): 3
shape: (3,)
size: 3


In [19]:
A = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(A)

print("len(A):", len(A))
print("shape:", A.shape)
print("size:", A.size)

[[10 20 30]
 [40 50 60]]
len(A): 2
shape: (2, 3)
size: 6
