# Array Creation

## Creating Arrays with `np.array()`

- `np.array()` creates a NumPy array from Python objects like lists or tuples.
- It is the most commonly used function to create arrays.

In [2]:
import numpy as np

In [3]:
A = np.array([10,20,30])
print(A)
print(type(A))

[10 20 30]
<class 'numpy.ndarray'>


## Why NumPy Arrays?

Python lists are general-purpose containers.

NumPy arrays are designed for numerical computing.

### NumPy Advantages

- Supports element-wise mathematical operations.
- Faster than Python lists for numerical computations.
- Memory efficient.
- Foundation for libraries like Pandas, TensorFlow, PyTorch, and Scikit-learn.

In [5]:
A = np.array([
    [10,20,30],
    [40,50,60]
])
print(A)

[[10 20 30]
 [40 50 60]]


In [7]:
A = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]  
])
print(A)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
A = np.array((10,20,30))
print(A)

[10 20 30]


In [15]:
A = np.array([1,2,3], dtype = float)
print(A)
print(A.dtype)

[1. 2. 3.]
float64


3D array with one table:

In [16]:
A = np.array([
    [
        [1,2],
        [3,4]
    ]
])
print(A)

[[[1 2]
  [3 4]]]


In [13]:
A = np.array((100,200,300))
print(A)

[100 200 300]


#

## np.zeros()

# Creating Arrays with `np.zeros()`

- `np.zeros()` creates a NumPy array filled with zeros.
- By default, the data type is `float64`.
- Useful for initialization in numerical computing and machine learning.

In [17]:
A = np.zeros(5)
print(A)
print(A.dtype)

[0. 0. 0. 0. 0.]
float64


In [18]:
A = np.zeros(10)
print(A)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [19]:
A = np.zeros((3,2))
print(A)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [21]:
A = np.zeros((2,2,2))
print(A)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
