# Array Creation

## Creating Arrays with `np.array()`

- `np.array()` creates a NumPy array from Python objects like lists or tuples.
- It is the most commonly used function to create arrays.

In [2]:
import numpy as np

In [3]:
A = np.array([10,20,30])
print(A)
print(type(A))

[10 20 30]
<class 'numpy.ndarray'>


## Why NumPy Arrays?

Python lists are general-purpose containers.

NumPy arrays are designed for numerical computing.

### NumPy Advantages

- Supports element-wise mathematical operations.
- Faster than Python lists for numerical computations.
- Memory efficient.
- Foundation for libraries like Pandas, TensorFlow, PyTorch, and Scikit-learn.

In [4]:
A = np.array([
    [10,20,30],
    [40,50,60]
])
print(A)

[[10 20 30]
 [40 50 60]]


In [5]:
A = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]  
])
print(A)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
A = np.array((10,20,30))
print(A)

[10 20 30]


In [7]:
A = np.array([1,2,3], dtype = float)
print(A)
print(A.dtype)

[1. 2. 3.]
float64


3D array with one table:

In [8]:
A = np.array([
    [
        [1,2],
        [3,4]
    ]
])
print(A)

[[[1 2]
  [3 4]]]


In [9]:
A = np.array((100,200,300))
print(A)

[100 200 300]


#

## np.zeros()

# Creating Arrays with `np.zeros()`

- `np.zeros()` creates a NumPy array filled with zeros.
- By default, the data type is `float64`.
- Useful for initialization in numerical computing and machine learning.

In [10]:
A = np.zeros(5)
print(A)
print(A.dtype)

[0. 0. 0. 0. 0.]
float64


In [11]:
A = np.zeros(10)
print(A)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
A = np.zeros((3,2))
print(A)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [13]:
A = np.zeros((2,2,2))
print(A)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [14]:
A =np.zeros((4,5))
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
A = np.zeros((2,4,5))
print(A)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [16]:
A = np.zeros(6, dtype = int)
print(A)

[0 0 0 0 0 0]


## Creating Arrays with `np.ones()`

- `np.ones()` creates a NumPy array filled with ones.
- By default, the data type is `float64`.
- You can change the data type using the `dtype` parameter.

In [17]:
A = np.ones(5)

print(A)
print(A.dtype)

[1. 1. 1. 1. 1.]
float64


In [18]:
A = np.ones((2,3))

print(A)

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
A = np.ones((2,2,2), dtype=int)

print(A)
print(A.dtype)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
int64


###

## Creating Arrays with `np.empty()`

- `np.empty()` creates an array without initializing its values.
- The array contains whatever data already exists in memory.
- It is faster than `zeros()` and `ones()` because NumPy does not fill the array.

In [20]:
A = np.empty(5)
print(A)

[1. 1. 1. 1. 1.]


In [21]:
A = np.empty(5)
B = np.empty(5)
C = np.empty(5)

print(A)
print(B)
print(C)

[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]


#

## Creating Arrays with `np.full()`

- `np.full()` creates an array filled with a specified value.
- Unlike `zeros()` and `ones()`, you can choose any value.
- You can also specify the data type using `dtype`.
- np.full(shape, fill_value)

In [22]:
A = np.full(3,4)
print(A)

[4 4 4]


In [23]:
A = np.full((2,3), 5)
print(A)

[[5 5 5]
 [5 5 5]]


In [24]:
A = np.full((4,4),"Hello")
print(A)

[['Hello' 'Hello' 'Hello' 'Hello']
 ['Hello' 'Hello' 'Hello' 'Hello']
 ['Hello' 'Hello' 'Hello' 'Hello']
 ['Hello' 'Hello' 'Hello' 'Hello']]


###

## Creating Arrays with `np.arange()`

- `np.arange()` creates an array with evenly spaced values.
- Similar to Python's `range()`, but returns a NumPy array.
- Commonly used for indexing, loops, plotting, and machine learning.

### Syntax

```python
np.arange(stop)
np.arange(start, stop)
np.arange(start, stop, step)
```

### Rules

- Starts from `start` (default is `0`).
- Stops **before** `stop`.
- Moves by `step` (default is `1`).
- `step` can be positive, negative, or a float.

In [25]:
A = np.arange(5)
print(A)
print(type(A))

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [26]:
A = np.arange(2,10,2)
print(A)

[2 4 6 8]


In [27]:
A = np.arange(0,10,2)
print(A)

[0 2 4 6 8]


In [28]:
A = np.arange(5,30,5)
print(A)

[ 5 10 15 20 25]


In [29]:
A = np.arange(10,4,-1)
print(A)

[10  9  8  7  6  5]


In [30]:
A = np.arange(1, 2, 0.2)
print(A)

[1.  1.2 1.4 1.6 1.8]


Start = 1....
Step = 0.2....
NumPy keeps adding 0.2

#

## Creating Arrays with `np.linspace()`

- `np.linspace()` creates evenly spaced values between a start and stop value.
- Unlike `np.arange()`, you specify the **number of values**, not the step size.
- By default, the stop value is included.

In [32]:
A = np.linspace(0,10,6)
print(A)

[ 0.  2.  4.  6.  8. 10.]


In [33]:
A = np.linspace(10,20,6)
print(A)

[10. 12. 14. 16. 18. 20.]


In [34]:
A = np.linspace(0,100,5)
print(A)

[  0.  25.  50.  75. 100.]


In [35]:
A = np.linspace(0,1,11)
print(A)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [36]:
A = np.linspace(100,200,5)
print(A)

[100. 125. 150. 175. 200.]


 ### endpoint=True (default) and endpoint=False does not include the stop or last element.

In [37]:
A = np.linspace(0,10,6, endpoint=False)
print(A)

[0.         1.66666667 3.33333333 5.         6.66666667 8.33333333]


#

## Creating Arrays with `np.eye()`

- `np.eye()` creates an identity matrix.
- An identity matrix has `1`s on the main diagonal and `0`s everywhere else.
- By default, the matrix is square (same number of rows and columns).

In [38]:
A = np.eye(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
A = np.eye(5)
print(A)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


np.eye(rows, columns)

In [40]:
A = np.eye(3,5)
print(A)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


There are only 3 ones, because there are only 3 rows.

In [41]:
A = np.eye(4,5)
print(A)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [42]:
A = np.eye(3,5)
print(A)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [43]:
A = np.eye(4, k=1)
print(A)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


k = 1
Move the diagonal one column to the right.

k = -1 → move the diagonal one column to the left

In [44]:
A = np.eye(4, k=-1)
print(A)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [45]:
A = np.eye(5)
print(A)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#

## Creating Arrays with `np.identity()`

- `np.identity()` creates a square identity matrix.
- It is similar to `np.eye()`, but only creates square matrices.

In [46]:
A = np.identity(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
