# Arithmetic Operations on NumPy Arrays

- NumPy performs arithmetic operations element by element.
- Arrays must usually have the same shape.
- Operations are much faster than using Python loops.

## Basic Arithmetic Operations

NumPy performs arithmetic element by element.

Supported operations:

- `+` → Addition
- `-` → Subtraction
- `*` → Multiplication
- `/` → Division
- `**` → Power
- `%` → Modulus
- `//` → Floor Division

In [2]:
import numpy as np

In [3]:
A = np.array([10, 20, 30])
B = np.array([2, 5, 10])

print("Addition      :", A + B)
print("Subtraction   :", A - B)
print("Multiplication:", A * B)
print("Division      :", A / B)
print("Power         :", A ** 2)
print("Modulus       :", A % B)
print("Floor Division:", A // B)

Addition      : [12 25 40]
Subtraction   : [ 8 15 20]
Multiplication: [ 20 100 300]
Division      : [5. 4. 3.]
Power         : [100 400 900]
Modulus       : [0 0 0]
Floor Division: [5 4 3]


In [4]:
A = np.array([10,20,30])

print(A + 5)
print(A - 5)
print(A % 5)
print(A * 5)
print(A / 5)

[15 25 35]
[ 5 15 25]
[0 0 0]
[ 50 100 150]
[2. 4. 6.]


### NumPy broadcasts the single value 5 across the array internally.

### This is called broadcasting.

# Broadcasting

- Broadcasting allows NumPy to perform operations on arrays of different shapes.
- Instead of copying data, NumPy automatically stretches dimensions when possible.
- Broadcasting makes code shorter, faster, and avoids unnecessary loops.

In [5]:
A = np.array([[10],
              [20],
              [30]])

B = np.array([1,2,3])

print(A)
print(A.shape)

print(B)
print(B.shape)

print(A + B)

[[10]
 [20]
 [30]]
(3, 1)
[1 2 3]
(3,)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [6]:
A = np.array([10, 20, 30, 40, 50])
B = 7
print(A+B)

[17 27 37 47 57]


In [8]:
A = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
B = np.array([1, 2, 3])
print(A+B)

[[11 22 33]
 [41 52 63]]


In [11]:
A = np.array([
    [70,80,90],
    [60,75,85]               
])
B = np.array([5,3,2])
print(A+B)

[[75 83 92]
 [65 78 87]]


In [12]:
A = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120],
])
B = np.array([
    [10],
    [20],
    [30]
])
print(A+B)

[[ 20  30  40  50]
 [ 70  80  90 100]
 [120 130 140 150]]


In [13]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
B = np.array([0.90, 0.80, 0.95])
print(A * B)

[[ 0.9   1.6   2.85]
 [ 3.6   4.    5.7 ]
 [ 6.3   6.4   8.55]
 [ 9.    8.8  11.4 ]]


In [14]:
A = np.array([
    [30, 32, 31],
    [25, 27, 26],
    [35, 36, 34],
    [20, 22, 21]
])
B = np.array([+2,-1,+3])
print(A+B)

[[32 31 34]
 [27 26 29]
 [37 35 37]
 [22 21 24]]


In [15]:
A = np.array([
    [70, 80, 90, 85],
    [60, 75, 88, 92],
    [95, 89, 78, 84]
])
B = np.array([
    [+5],
    [-3],
    [+10]
])
print(A+B)

[[ 75  85  95  90]
 [ 57  72  85  89]
 [105  99  88  94]]


In [16]:
A = np.array([
    [20, 25, 30],
    [22, 27, 32],
    [18, 24, 29],
    [21, 26, 31]
])
F = A * 9/5 + 32
print(F)

[[68.  77.  86. ]
 [71.6 80.6 89.6]
 [64.4 75.2 84.2]
 [69.8 78.8 87.8]]


#

## Indexing and Slicing

In [17]:
A = np.array([10, 20, 30, 40, 50])

print(A[0])
print(A[2])
print(A[-1])

10
30
50


In [18]:
print(A[3])
print(A[0])
print(A[4])

40
10
50


In [26]:
A = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(A[1,2])
print(A[2,0])
print(A[0,1])

60
70
20


In [27]:
A = np.array([10, 20, 30, 40, 50, 60])
print(A[1:2])
print(A[2:3]) 
print(A[3:4])

[20]
[30]
[40]


In [3]:
A = np.array([10, 20, 30, 40, 50, 60])
print(A[2:6])

[30 40 50 60]


In [6]:
A = np.array([10, 20, 30, 40, 50, 60])
print(A[-1:0:-1])

[60 50 40 30 20]


In [9]:
A = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])
print(A[1:4,2:4])

[[ 70  80]
 [110 120]
 [150 160]]
