# Arithmetic Operations on NumPy Arrays

- NumPy performs arithmetic operations element by element.
- Arrays must usually have the same shape.
- Operations are much faster than using Python loops.

## Basic Arithmetic Operations

NumPy performs arithmetic element by element.

Supported operations:

- `+` → Addition
- `-` → Subtraction
- `*` → Multiplication
- `/` → Division
- `**` → Power
- `%` → Modulus
- `//` → Floor Division

In [1]:
import numpy as np

A = np.array([10, 20, 30])
B = np.array([2, 5, 10])

print("Addition      :", A + B)
print("Subtraction   :", A - B)
print("Multiplication:", A * B)
print("Division      :", A / B)
print("Power         :", A ** 2)
print("Modulus       :", A % B)
print("Floor Division:", A // B)

Addition      : [12 25 40]
Subtraction   : [ 8 15 20]
Multiplication: [ 20 100 300]
Division      : [5. 4. 3.]
Power         : [100 400 900]
Modulus       : [0 0 0]
Floor Division: [5 4 3]


In [2]:
A = np.array([10,20,30])

print(A + 5)
print(A - 5)
print(A % 5)
print(A * 5)
print(A / 5)

[15 25 35]
[ 5 15 25]
[0 0 0]
[ 50 100 150]
[2. 4. 6.]


### NumPy broadcasts the single value 5 across the array internally.

### This is called broadcasting.

# Broadcasting

- Broadcasting allows NumPy to perform operations on arrays of different shapes.
- Instead of copying data, NumPy automatically stretches dimensions when possible.
- Broadcasting makes code shorter, faster, and avoids unnecessary loops.